timesheet/lib/timesheet_web/router.ex
defmodule TimesheetWeb.Router do
  use TimesheetWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug TimesheetWeb.Plugs.FetchCurrentManager
    plug TimesheetWeb.Plugs.FetchCurrentWorker
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TimesheetWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/tasks/checkstatus", TaskController, :timesheetStatus
    resources "/managers", ManagerController,
    only: [:index]
    resources "/workers", WorkerController,
    only: [:index]
    resources "/sessionmanager", SessionmanagerController, 
    only: [:new, :create, :delete], singleton: true
    resources "/sessionworker", SessionworkerController, 
    only: [:new, :create, :delete], singleton: true
    resources "/jobs", JobController,
    only: [:index, :new, :create]
    resources "/tasks", TaskController
  end

  # Other scopes may use custom stacks.
  # scope "/api", TimesheetWeb do
  #   pipe_through :api
  # end
end

timesheet/lib/timesheet/managers.ex
defmodule Timesheet.Managers do
  @moduledoc """
  The Managers context.
  """

  import Ecto.Query, warn: false
  alias Timesheet.Repo

  alias Timesheet.Managers.Manager

  @doc """
  Returns the list of managers.

  ## Examples

      iex> list_managers()
      [%Manager{}, ...]

  """
  def list_managers do
    #query = from u in Manager, where u.name = "Alice"
    #Repo.all(from u in "managers", where: u.name == "Alice", select: u.name)
    Repo.all(Manager)
  end

  @doc """
  Gets a single manager.

  Raises `Ecto.NoResultsError` if the Manager does not exist.

  ## Examples

      iex> get_manager!(123)
      %Manager{}

      iex> get_manager!(456)
      ** (Ecto.NoResultsError)

  """
  def get_manager!(id), do: Repo.get!(Manager, id)


  def get_manager_by_email(email) do
    Repo.get_by(Manager, email: email)
  end

  def get_manager(id), do: Repo.get(Manager, id)

  def authenticate(email, pass) do
    user = Repo.get_by(Manager, email: email)
    case Argon2.check_pass(user, pass) do
      {:ok, user} -> user
      _ -> nil
    end
end
  @doc """
  Creates a manager.

  ## Examples

      iex> create_manager(%{field: value})
      {:ok, %Manager{}}

      iex> create_manager(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_manager(attrs \\ %{}) do
    %Manager{}
    |> Manager.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a manager.

  ## Examples

      iex> update_manager(manager, %{field: new_value})
      {:ok, %Manager{}}

      iex> update_manager(manager, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_manager(%Manager{} = manager, attrs) do
    manager
    |> Manager.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Manager.

  ## Examples

      iex> delete_manager(manager)
      {:ok, %Manager{}}

      iex> delete_manager(manager)
      {:error, %Ecto.Changeset{}}

  """
  def delete_manager(%Manager{} = manager) do
    Repo.delete(manager)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking manager changes.

  ## Examples

      iex> change_manager(manager)
      %Ecto.Changeset{source: %Manager{}}

  """
  def change_manager(%Manager{} = manager) do
    Manager.changeset(manager, %{})
  end
end

timesheet/lib/timesheet/managers/manager.ex
defmodule Timesheet.Managers.Manager do
  use Ecto.Schema
  import Ecto.Changeset

  schema "managers" do
    field :email, :string
    field :name, :string
    field :password_hash, :string



    timestamps()
  end

  @doc false
  def changeset(manager, attrs) do
    manager
    |> cast(attrs, [:email, :name, :password_hash])
    |> validate_required([:email, :name, :password_hash])
    |> validate_length(:password_hash, min: 8) # too short
    |> hash_password()
  end

  def hash_password(cset) do
    pw = get_change(cset, :password_hash)
    if pw do
      change(cset, Argon2.add_hash(pw))
    else
      cset
    end
  end
end

timesheet/lib/timesheet_web/controllers/manager_controller.ex
defmodule TimesheetWeb.ManagerController do
  use TimesheetWeb, :controller

  alias Timesheet.Managers
  alias Timesheet.Managers.Manager

  def index(conn, _params) do
    managers = Managers.list_managers()
    IO.inspect(managers)
    render(conn, "index.html", managers: managers)
    
  end

  def new(conn, _params) do
    changeset = Managers.change_manager(%Manager{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"manager" => manager_params}) do
    IO.inspect(manager_params)
    case Managers.create_manager(manager_params) do
      {:ok, manager} ->
        conn
        |> put_flash(:info, "Manager created successfully.")
        |> redirect(to: Routes.manager_path(conn, :show, manager))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    manager = Managers.get_manager!(id)
    render(conn, "show.html", manager: manager)
  end

  def edit(conn, %{"id" => id}) do
    manager = Managers.get_manager!(id)
    changeset = Managers.change_manager(manager)
    render(conn, "edit.html", manager: manager, changeset: changeset)
  end

  def update(conn, %{"id" => id, "manager" => manager_params}) do
    manager = Managers.get_manager!(id)

    case Managers.update_manager(manager, manager_params) do
      {:ok, manager} ->
        conn
        |> put_flash(:info, "Manager updated successfully.")
        |> redirect(to: Routes.manager_path(conn, :show, manager))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", manager: manager, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    manager = Managers.get_manager!(id)
    {:ok, _manager} = Managers.delete_manager(manager)

    conn
    |> put_flash(:info, "Manager deleted successfully.")
    |> redirect(to: Routes.manager_path(conn, :index))
  end
end

timesheet/lib/timesheet_web/views/manager_view.ex
defmodule TimesheetWeb.ManagerView do
  use TimesheetWeb, :view
end

timesheet/lib/timesheet_web/templates/manager/edit.html.eex
<h1>Edit Manager</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.manager_path(@conn, :update, @manager)) %>

<span><%= link "Back", to: Routes.manager_path(@conn, :index) %></span>

timesheet/lib/timesheet_web/templates/manager/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

<div class="form-group">
  <%= label f, :email %>
  <%= text_input f, :email, class: "form-control" %>
  <%= error_tag f, :email %>
</div>
<div class="form-group">
  <%= label f, :name %>
  <%= text_input f, :name, class: "form-control"%>
  <%= error_tag f, :name %>
</div>

  <div class="form-group">
    <%= label f, :password %>
    <%= password_input f, :password, class: "form-control" %>
    <%= error_tag f, :password %>
  </div>
  
<div class="form-group">
  <div>
    <%= submit "Save" , class: "btn btn-primary"%>
  </div>
</div>  
<% end %>

timesheet/lib/timesheet_web/templates/manager/index.html.eex
<h2> Managers Home Page</h2>
(<span><%= link("Sign Out", to: Routes.sessionmanager_path(@conn, :delete),
              method: :delete) %>)</span>



<h2>View Jobs for the Employees</h2>

<span><%= link "Add Jobs", to: Routes.job_path(@conn, :new) %></span>


<h2>Approve Timesheets for the Employees</h2>

<span><%= link "Approve Timesheets", to: Routes.task_path(@conn, :index) %></span>

timesheet/lib/timesheet_web/templates/manager/new.html.eex
<h1>New Manager</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.manager_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.manager_path(@conn, :index) %></span>

timesheet/lib/timesheet_web/templates/manager/show.html.eex
<h1>Show Manager</h1>

<ul>

  <li>
    <strong>Email:</strong>
    <%= @manager.email %>
  </li>

  <li>
    <strong>Name:</strong>
    <%= @manager.name %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.manager_path(@conn, :edit, @manager) %></span>
<span><%= link "Back", to: Routes.manager_path(@conn, :index) %></span>